### ISSUE TITLE
Rendering glich when bar is wider than console

### ISSUE THREAD

**Issue by joeyh** [yamadapc/haskell-ascii-progress#5]
I tried the Example on an 75 column display, and while it was running, there was a display glitch that appeared like this.

   Working   0% [                                                ]   0/ 20 (fo
   Working  35% [=================                               ]   7/ 20 (fo

Suggest truncating the display to the number of columns.

**Comment by yamadapc** [comment]
To the number of columns in the console, you mean?

I figured it was best to leave detecting the terminal's size to the users, since doing it in a cross-platform way is the kind of thing that deserves it's own package and I didn't want to introduce the dependency. There's a `terminal-size` package on Hackage that does this ([here](https://hackage.haskell.org/package/terminal-size)). I'll update the examples to use it. It has no dependencies... Maybe that could be exposed as an option?

**Comment by joeyh** [comment]
Pedro Tacla Yamada wrote:
> To the number of columns in the console, you mean?

Correct, the width of the console.

I think it's fine for you to punt on this one. I did find it a bit
surprising that it wasn't console width aware.

-- 
see shy jo
