### ISSUE TITLE
visual glitch with many progress bars scrolling up screen

### ISSUE THREAD

**Issue by joeyh** [yamadapc/haskell-ascii-progress#8]
I modified MultiExample.hs in 2 ways for this test:

1. Reduced the delays so the bars update 1000 times faster.
2. Made main recursively call main once all progress bars were updated.

This image shows the visual glitch that resulted from the resulting stream of progress bars.

http://tmp.kitenet.net/multimultibug.png

I see this in multiple different terminal emulators (eg, gnome-terminal). It seems to be somewhat timing dependent, ie changing the *1000 in the delay to * 10 doesn't produce it, but * 1 does.

BTW, the original goal in this test was to check if there were any memory leaks when using enormous numbers of progress bars. Good job -- no memory leaks found!

**Comment by joeyh** [comment]
Probably this is just 2 progress bars updating at the same time and outputting to console at the same time.

**Comment by joeyh** [comment]
I have git-annex using ascii-progress now. This bug is one of the blockers for merging that into git-annex:master

**Comment by yamadapc** [comment]
Looking at this

**Comment by yamadapc** [comment]
I'll need to use a VM to reproduce this, because nor `iTerm` nor `Terminal` have this problem on OSX. I'll make a fix by tomorrow, then bump and republish with the other improvements. GHC 7.6.2 (and 7.6.1) support is still pending, [because of some weird `hspec` problem](). Hopefully if I can set-up a decent virtual environment this will be easier to understand.

I'm going to limit the amount of updates done per second too, maybe have a single writer-thread after all. Maybe that fixes it.

Let me try to understand this better. You tweaked the `multi-example` to be faster and have a recursive call to `main` before the three `wait` calls or after them? Can you send me your tweaked `MultiExample.hs`?

**Comment by joeyh** [comment]
Pedro Tacla Yamada wrote:
> Let me try to understand this better. You tweaked the multi-example to be
> faster and have a recursive call to main before the three wait calls or after
> them? Can you send me your tweaked MultiExample.hs?

I've attached it.

In extreme cases (when git-annex is driving it), the concurrent writers can
overlap completely, I've seen output that includes things like this:
          
E [   TE1EEEATGTTT AAAA          N    aNNNNNaaaa

This was 6 threads all printing out something like ETA NaN.

This is on Linux BTW.

Basically the same as:

Prelude> import Control.Concurrent
Prelude> forkIO (print (repeat 'a')) >> forkIO (print (repeat 'b'))
abababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababa

-- 
see shy jo
